apiVersion: eksctl.io/v1alpha3
kind: ClusterConfig
metadata:
  name: prometheus-poc
  region: us-east-2
  version: "1.11"
nodeGroups:
- name: ng-1
  instanceType: t3.large
  privateNetworking: false
  desiredCapacity: 2
  minsSize: 2
  maxSize: 3
