---
apiVersion: v1
kind: Pod
metadata:
    name: gitrepo-vol-pod
spec:
  containers:
  - image: nginx:1.15.7-alpine
    name: web-server
    volumeMounts:
    - name: html
      mountPath: /usr/share/nginx/html
      readOnly: true
    ports:
    - containerPort: 80
      protocol: TCP

  volumes:
  - name: html
    gitRepo:
      repository: https://github.com/alejandrox1/kubia-website-example
      revision: master
      directory: .
