- hosts: master
  become: yes
  become_user: root
  become_method: sudo
  gather_facts: false
  tasks:
      - name: Get join command
        shell: kubeadm token create --print-join-command
        register: join_command_raw

      - name: Set join command
        set_fact:
            join_command: "{{ join_command_raw.stdout_lines[0] }}"


- hosts: workers
  become: yes
  become_user: root
  become_method: sudo
  tasks:
      - name: Join cluster
        shell: "{{ hostvars['master'].join_command }} >> node_joined.txt"
        args:
            chdir: $HOME
            creates: node_joined.txt
