---
apiVersion: v1
kind: Pod
metdata:
  name: fortune-cm
spec:
  containers:
  - image: alejandrox1/fortune:v1.2.0
    name: html-generator
    envFrom:
    - prefix: config
      configMapRef:
        name: fortune-config
    args: ["$(config_sleep_interval)"]
    volumeMounts:
    - name: html
      mountPath: /var/htdocs

  - image: nginx:1.15.7-alpine
    name: web-server
    volumeMounts:
    - name: config
      mountPath: /etc/nginx/conf.d/
      subPath: nginx-config.conf 
      readOnly: true
    - name: html
      mountPath: /usr/share/nginx/html
      readOnly: true
    ports:
    - containerPort: 80
      protocol: TCP

  volumes:
  - name: config
    configMap:
      name: nginx-config
      items:
      - key: nginx-config.conf
        path: gzip.conf

  - name: html
    emptyDir: {}
