---
apiVersion: v1
kind: Pod
metadata:
  name: fortune-env
spec:
  containers:
  - image: alejandrox1/fortune:v1.2.0
    name: html-generator
    env:
    - name: INTERVAL
      value: "15"
    volumeMounts:
    - name: html
      mountPath: /var/htdocs

  - image: nginx:1.15.7-alpine
    name: web-server
    volumeMounts:
    - name: html
      mountPath: /usr/share/nginx/html
      readOnly: true
    ports:
    - containerPort: 80
      protocol: TCP

  volumes:
  - name: html
    emptyDir: {}
