apiVersion: batch/v1
kind: Job
metadata:
    name: oneshot
    labels:
        chapter: jobs
spec:
    template:
        metadata:
            labels:
                chapter: jobs
        spec:
            containers:
                - name: kuard
                image: gcr.io/kuard-demo/kuard-demo-amd64:1
                imagePullPolicy: Always
                args:
                    - "--keygen-enable"
                    - "--keygen-exit-on-complete"
                    - "--keygen-num-to-gen=10"
            restartPolicy: OnFailure
                 
