apiVersion: batch/v1
kind: Job
metadata:
    name: parallel
    labels:
        chapter: jobs
spec:
    parallelism: 5
    completions: 10
    template:
        metadata:
            labels:
                chapter: jobs
        spec:
            containers:
              - name: kuard
                image: gcr.io/kuard-demo/kuard-amd64:1
                imageullPolicy: Always
                args:
                    - "--keygen-enable"
                    - "--keygen-exit-on-complete"
                    - "--keygen-num-to-gen=10"
            restartPolicy: OnFailure
