apiVersion: extensions/v1beta1
kind: ReplicaSet
metadata:
    name: mysql
    # Labels to bind a Service to this pod.
    labels:
        app: mysql
spec:
    replicas: 1
    selector:
        matchLabels:
            app: mysql
    template:
        metadta:
            labels:
                app: mysql
        spec:
            containers:
              - name: database
                image: mysql
                resources:
                    requests:
                        cpu: 1
                        memory: 2Gi
                env:
                  - name: MYSQL_ROOT_PASSWORD
                    value: some-password-here
                livelinessProbe:
                    tcpSocket:
                        port: 3306
                ports:
                  - containerPort: 3306
                volumeMounts:
                    name: database
                    mountPath: "/var/lib/mysql"
            volumes:
              - name: database
                persistentVolumeClaim:
                    claimName: database
