---
apiVersion: v1
kind: Pod
metadata:
    name: kubia-manual
spec:
    containers:
        - image: alejandrox1/kubia:v1.0.0
          name: kubia
          ports:
              - containerPort: 8080
                protocol: TCP
