version: "3"

networks:
    publicnet:
        driver: bridge

    intranet:

services:
    vault:
        build: ./vault/
        hostname: vault
        container_name: vault
        environment:
            VAULT_ADDR: http://0.0.0.0:8200
        cap_add:
            - IPC_LOCK
        volumes:
            - ./vault/vault:/vault
            - ./vault/policies:/policies
        networks:
            - publicnet
        ports:
            - 8200:8200

    db:
        build: ./db/
        hostname: db
        container_name: db
        restart: always
        environment:
            POSTGRES_USER: admin                                           
            POSTGRES_PASSWORD: admin                                           
            POSTGRES_DB: db
        networks:
            - intranet
        ports:
            - 5432:5432

    adminer:
        image: adminer
        restart: always
        hostname: adminer
        container_name: adminer
        networks:
            - intranet
        ports:
            - 8080:8080

    server:
        build: ./server/ 
        hostname: server
        container_name: server
        volumes:
            - ./vault/configs:/vault/configs
        networks:
            - intranet
            - publicnet
        ports:
            - 8000:8000
