# vi: set ft=ruby

# OS.
VAGRANT_BOX = 'ubuntu/trusty64'

# Name for VM.
VM_NAME = 'new-vm'

# VM user - 'vagrant' by default.
VM_USER = 'vagrant'

# User name on host.
HOST_USER = 'alarcj'

# Host folder to sync to.
HOST_PATH = '/home/' + HOST_USER + '/go/src/github.com/alejandrox1/cool_go/containers/docker-tutorial/vm-vagrant/vol'

# Guest folder to sync to.
GUEST_PATH = '/home/' + VM_USER + '/' + VM_NAME

# VM port - uncomment this to use NAT instead of DHCP
# VM_PORT = 8080

Vagrant.configure("2") do |config|
    # Vagrant box from Hashicorp
    config.vm.box = VAGRANT_BOX

    # Machine name
    config.vm.hostname = VM_NAME

    # Set VM using VirtualBox
    config.vm.provider "virtualbox" do |v|
        v.name = VM_NAME
        v.memory = 2048
    end

    # DHCP - comment out if using NAT
    config.vm.network "private_network", type: "dhcp"

    # Port forwarding - uncomment this to use NAT instead of DHCP
    # config.vm.network "forwarded_port", guest: 80, host: VM_PORT
    
    # Sync folder
    config.vm.synced_folder HOST_PATH, GUEST_PATH

    # Disable default vagrant folder
    config.vm.synced_folder '.', 'home' + VM_USER + '', disabled: true

    # Install Git, Node.js 6.x.x, Latest npm
    config.vm.provision "shell", inline: <<-SHELL
        apt-get update
        apt-get install -y git
        curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
        apt-get install -y nodejs
        apt-get install -y build-essential
        npm install -g npm
        apt-get update
        apt-get upgrade -y
        apt-get autoremove -y
    SHELL
end
