apiVersion: extensions/v1beta1
kind: Deployment
metadata:
    annotations:
        deployment.kubernetes.io/revision: "1"
    labels:
        run: nginx
    name: nginx
    namespace: default
spec:
    replicas: 2
    revisionHistoryLimit: 14
    minReadySeconds: 60
    progressDeadlineSeconds: 600
    selector:
        matchLabels:
            run: nginx
    strategy:
        rollingUpdate:
            maxSurge: 1
            maxUnavailable: 1
        type: RollingUpdate
    template:
        metadata:
            labels:
                run: nginx
        spec:
            containers:
              - image: nginx:1.7.12
                imagePullPolicy: Always
            dsnPolicy: ClusterFirst
            restartPolicy: Always
