apiVersion: extensions/v1beta1
kind: ReplicaSet
metadata:
    name: kuard
spec:
    replicas: 1
    template:
        metadata:
            labels:
                app: kuard
                version: "2"
        spec:
            containters:
                - name: kuard
                image: "gcr.io/kuard-demo/kuard-demo-amd64:2"
